spring:
  application:
    name: trip_planner
  profiles:
    group:
      local: local
      dev: dev
      prod: prod

---
spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug